trigger:
  - master
pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest
steps:
  - task: Docker@2
    displayName: build docker image
    inputs:
      command: 'build'
      tags: '$(Build.BuildId)'
      repository: 'hema789/chaitu'
  - task: Docker@2
    inputs:
      command: 'push'
      Dockerfile: '**/Dockerfile'
      containerRegistry: 'Docker Hub'
      repository: 'hema789/chaitu'